#!/usr/bin/env bash
# Generate one Herdr Plus project TOML per folder in CODING_DIR
set -euo pipefail

CODING_DIR="${CODING_DIR:-$HOME/Documents/Coding}"
PROJECTS_DIR="$(cd "$(dirname "$0")" && pwd)"
GENERATED_MARKER="# generated by sync-coding-projects.sh"

# Folder names whose project files sync will not overwrite or delete.
PROTECTED=(
)

# Folder names in CODING_DIR that should not get a generated project file.
IGNORE=(
)

in_list() {
    local folder="$1"
    shift
    local name
    (($#)) || return 1
    for name in "$@"; do
        [[ "$folder" == "$name" ]] && return 0
    done
    return 1
}

protected() {
    in_list "$1" "${PROTECTED[@]+"${PROTECTED[@]}"}"
}

ignored() {
    in_list "$1" "${IGNORE[@]+"${IGNORE[@]}"}"
}

is_keep() {
    printf '%s\n' "$keep_files" | grep -qx "$1"
}

if [[ ! -d "$CODING_DIR" ]]; then
    echo "coding directory not found: $CODING_DIR" >&2
    exit 1
fi

keep_files=""

for dir in "$CODING_DIR"/*/; do
    [[ -d "$dir" ]] || continue
    name="$(basename "$dir")"
    [[ "$name" == .* ]] && continue
    ignored "$name" && continue

    file="${name}.toml"
    keep_files="${keep_files}${file}"$'\n'
    protected "$name" && continue

    cat >"$PROJECTS_DIR/$file" <<EOF
$GENERATED_MARKER
name = "$name"
description = "$name (New Workspace)"
group = "Projects/"
working_dir = "~/Documents/Coding/$name"

[[tabs]]
name = "1"

[[tabs]]
name = "agent"
command = "agent"

[[tabs]]
name = "hunk"
command = "hunk diff"
EOF
done

for path in "$PROJECTS_DIR"/*.toml; do
    [[ -f "$path" ]] || continue
    file="$(basename "$path")"
    protected "${file%.toml}" && continue
    is_keep "$file" && continue
    if [[ "$(head -n 1 "$path")" == "$GENERATED_MARKER" ]]; then
        rm -f "$path"
    fi
done
